export const types = {
  authcheckingStart: '[auth] Start checking login state',
  authcheckingFinish: '[auth] Finish checking login state',
  authStartLogin: '[auth] Start login',
  authlogin: '[auth] Login',
  authStartRegister: '[auth] Start register',
  authStartTokenRenew: '[auth] Start token renew',
  authlogout: '[auth] Logout',
  authShowLogin: '[auth] Show Login form',
  authShowRegister: '[auth] Show Register form',
  authShowPassForgot: '[auth] Show Password Forgot form',

  uiStartLoading: '[ui] Start loading',
  uiFinishLoading: '[ui] Finish loading',
  uiSetCurrentPath: '[ui] Set Current Path',
  uiSetContentBackground: '[ui] Set Content Background',
  uiSetContentStyles: '[ui] Set Content styles',

  productSetActive: '[product] Set active',
  productClearActive: '[product] Clear active',
  productStartAddNew: '[product] Start add new',
  productAddNew: '[product] Add New',
  productClearActivePoduct: '[product] Clear active product',
  productUpdated: '[product] product updated',
  productDeleted: '[product] product deleted',
  productLoaded: '[product] Loaded products',
  productclearProductsLoaded: '[product] clear Loaded products',
  productAddedForSale: '[product] added for sale',
  productSetProductsForSale: '[product] set products for sale',
  productClearProductsForSale: '[product] clear products for sale',

  customersLoaded: '[customer] Loaded customers',
  customerSetActiveCustomer: '[customer] Set active customer',
  customerClearActiveCustomer: '[customer] clear active customer',
  clearCustomersLoaded: '[customer] Clear customers loaded',

  trademarksLoaded: '[trademarks] Loaded Trademarks',
  trademarksAddNew: '[trademarks] Add new Trademark title',
  trademarksTitles: '[trademarks] Trademark titles',

  billingSetBillingData: '[billing] set billing data',
  billingClearBillingData: '[billing] clear billing data',
  billingUpdatePaymentConditions: '[billing] update payment conditions',

  displayGeneratePdf: '[show] Generate pdf',
  displayFormCustomer: '[show] Customer Form',
  displayFormTrademark: '[show] Trademark Form',
  displayFormProduct: '[show] Product Form',
};
