export const types = {
  authcheckingFinish: '[auth] Finish checking login state',
  authStartLogin: '[auth] Start login',
  authlogin: '[auth] Login',
  authStartRegister: '[auth] Start register',
  authStartTokenRenew: '[auth] Start token renew',
  authlogout: '[auth] Logout',
  authShowLogin: '[auth] Show Login form',
  authShowRegister: '[auth] Show Register form',
  authShowPassForgot: '[auth] Show Password Forgot form',

  uiCloseModal: '[UI] Close modal',
  uiFinishLoading: '[UI] Finish loading',
  uiOpenModal: '[UI] Open modal',
  uiSetCurrentPath: '[ui] Set Current Path',
  uiSetContentBackground: '[ui] Set Content Background',
  uiStartLoading: '[UI] Start loading',

  productSetActive: '[product] Set active',
  productClearActive: '[product] Clear active',
  productStartAddNew: '[product] Start add new',
  productAddNew: '[product] Add New',
  productClearActivePoduct: '[product] Clear active product',
  productUpdated: '[product] product updated',
  productDeleted: '[product] product deleted',
  productLoaded: '[product] Loaded products',
  productclearProductsLoaded: '[product] clear Loaded products',
  productAddedForSale: '[product] added for sale',
  productSetProductsForSale: '[product] set products for sale',
  productClearProductsForSale: '[product] clear products for sale',

  customersLoaded: '[customer] Loaded customers',
  customerSetActiveCustomer: '[customer] Set active customer',
  customerClearActiveCustomer: '[customer] clear active customer',
  clearCustomersLoaded: '[customer] Clear customers loaded',

  transactionSetTransactionData: '[invoice] set transaction data',
  transactionClearTransactionData: '[invoice] clear transaction data',
  transactionUpdatePaymentConditions: '[invoice] update payment conditions',

  displayGeneratePdf: '[display] Generate pdf',
  displayFormCustomerAdd: '[display] Add Customer Form',
  displayFormProductAdd: '[display] Add Product Form',
};
